x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-info}
  
services:
  app:
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vapor-app
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    volumes:
      - ./Public:/app/Public:ro
    networks:
      - vapor-network
    restart: always
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

networks:
  vapor-network:
    driver: bridge
